version: "3"

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt

  backend:
    build: ./backend
    volumes:
      - coinbin:/coinbin
    depends_on:
      - daemon
    command: bash -c "cp /coinbin/helium* /usr/local/bin/ && npm run db:migrations:run && node index.js"
    restart: always
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_SSL
      - JWT_SECRET
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=PRODUCTION
      - API_URL=http://backend:3000
      - TICKER=HLM
      - SITE_TITLE=Heliumlabs

  daemon:
    build: ./daemon
    volumes:
      - coinbin:/coinbin
    ports:
      - 8332:8332
    command: bash -c "cp /usr/local/bin/helium* /coinbin && /usr/local/bin/heliumd"
    restart: always

volumes:
  coinbin:
  letsencrypt: