version: "3"

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt

  backend:
    build: ./backend
    volumes:
      - coinbin:/coinbin
    depends_on:
      - daemon
    command: bash -c "cp /coinbin/helium* /usr/local/bin/ && node index.js"
    restart: always
    environment:
      - DB_HOST=db # override for docker-compose internal network
      - DB_SSL=true # use ssl connection for production db
      - MAILGUN_API_KEY # secret, set manually with $ export MAILGUN_API_KEY=[api-key]
      - MAILGUN_DOMAIN # secret, set manually with $ export MAILGUN_DOMAIN=[domain]

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=PRODUCTION
      - API_URL=http://backend:3000
      - TICKER=HLM
      - SITE_TITLE=Heliumlabs

  daemon:
    build: ./daemon
    volumes:
      - coinbin:/coinbin
    ports:
      - 8332:8332
    command: bash -c "cp /usr/local/bin/helium* /coinbin && /usr/local/bin/heliumd"
    restart: always

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: heliumlabs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  coinbin:
  letsencrypt: